### ISSUE TITLE
Eslint not working

### ISSUE THREAD

**Issue by doiya46** [CodingGarden/react-ts-starter#3]
1: `str` is define and dont use.
 
```ts
export function App({ str }: { str: string }) {
  return (
    <Routes>
      <Route path="/" element={<Home />} />
      <Route path="*" element={<NotFound />} />
    </Routes>
  );
}
```

2: `str` is required but eslint ignore

```ts
export function WrappedApp() {
  return (
    <HashRouter>
      <App />
    </HashRouter>
  );
}
```

![Screenshot from 2022-12-09 14-54-24](https://user-images.githubusercontent.com/61301244/206652844-5a893d16-dc53-422c-be9a-fb5d2e7abc73.png)

**Comment by w3cj** [comment]
1. This error is expected because the `str` prop is not used anywhere in the App component.
2. This is expected because `str` was not passed as a prop to the App component.

The way this project is configured, eslint errors will not break the vite build. If you'd like that behavior, you can use a plugin like this: https://github.com/gxmari007/vite-plugin-eslint#usage
